import { BUSINESS, LOCALE } from '../config/business';
import { formatDate } from './dates';
import { formatAmount, formatCurrency } from './currency';
import { getJobStatus, getQuoteStatus, getInvoiceStatus } from '../constants/statuses';

function escapeHtml(value) {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function statusBadge(status) {
  return `<span style="display:inline-block;padding:4px 12px;border-radius:999px;font-size:11px;font-weight:700;background:${status.bg};color:${status.color};border:1px solid ${status.color}30">${escapeHtml(status.label)}</span>`;
}

function printHTML(html) {
  const win = window.open('', '_blank');
  if (!win) {
    throw new Error('Popup blocked. Allow popups to export PDFs.');
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
}

export function exportJobReport(job, employees) {
  const status = getJobStatus(job.status);
  const team = employees.filter(e => job.assignedEmployees?.includes(e.id));
  const generatedAt = new Date().toLocaleString(LOCALE.date);

  const teamRows = team
    .map(e => `<div class="row"><span class="label">${escapeHtml(e.role)}</span><span>${escapeHtml(e.name)} — ${escapeHtml(e.phone)}</span></div>`)
    .join('');

  const html = `
    <html><head><title>${escapeHtml(BUSINESS.name)} — ${escapeHtml(job.referenceNumber || '')}</title><style>
      body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #1A1A18; max-width: 800px; margin: 0 auto; }
      h1 { font-size: 24px; margin-bottom: 4px; }
      .section { margin: 24px 0; }
      h2 { font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; color: #6B6B66; margin-bottom: 8px; border-bottom: 1px solid #E0DED8; padding-bottom: 6px; }
      .row { display: flex; gap: 8px; margin-bottom: 6px; font-size: 14px; }
      .label { color: #9E9E98; width: 120px; flex-shrink: 0; }
      .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #E0DED8; font-size: 11px; color: #9E9E98; }
    </style></head><body>
      <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px">
        <div>
          <div style="font-size:11px;color:#9E9E98;margin-bottom:4px;text-transform:uppercase;letter-spacing:0.08em">JOB REPORT${job.referenceNumber ? ' — ' + escapeHtml(job.referenceNumber) : ''}</div>
          <h1>${escapeHtml(job.contactName || 'Unnamed Job')}</h1>
          <div style="margin-top:8px">${statusBadge(status)}</div>
        </div>
        <div style="text-align:right;font-size:12px;color:#9E9E98">
          <div>${escapeHtml(BUSINESS.name)}</div>
          <div>${generatedAt}</div>
        </div>
      </div>
      ${job.description ? `<div style="font-size:14px;color:#6B6B66;margin-bottom:24px;padding:16px;background:#F5F4F0;border-radius:8px">${escapeHtml(job.description)}</div>` : ''}
      <div class="section">
        <h2>Job Details</h2>
        <div class="row"><span class="label">Address</span><span>${escapeHtml(job.address)}</span></div>
        <div class="row"><span class="label">Start</span><span>${formatDate(job.startDate)}${job.startTime ? ' ' + escapeHtml(job.startTime) : ''}</span></div>
        ${job.endDate ? `<div class="row"><span class="label">End</span><span>${formatDate(job.endDate)}${job.endTime ? ' ' + escapeHtml(job.endTime) : ''}</span></div>` : ''}
        ${job.notes ? `<div class="row"><span class="label">Notes</span><span>${escapeHtml(job.notes)}</span></div>` : ''}
      </div>
      ${(job.contactName || job.contactPhone || job.contactEmail) ? `
      <div class="section">
        <h2>Contact</h2>
        ${job.contactName ? `<div class="row"><span class="label">Name</span><span>${escapeHtml(job.contactName)}</span></div>` : ''}
        ${job.contactPhone ? `<div class="row"><span class="label">Phone</span><span>${escapeHtml(job.contactPhone)}</span></div>` : ''}
        ${job.contactEmail ? `<div class="row"><span class="label">Email</span><span>${escapeHtml(job.contactEmail)}</span></div>` : ''}
      </div>` : ''}
      ${team.length ? `<div class="section"><h2>Assigned Team (${team.length})</h2>${teamRows}</div>` : ''}
      <div class="footer">Generated by ${escapeHtml(BUSINESS.name)} · ${generatedAt}</div>
    </body></html>
  `;

  printHTML(html);
}

// Shared rendering for both quotes and invoices — they have identical layouts
// aside from the title, status palette, and date label.
function exportBillingDocument({ doc, kind, status, dateLabel, expiryLabel, expiryValue, numberLabel }) {
  const itemsHTML = (doc.items || []).map(item => `
    <tr>
      <td style="padding:8px 10px;border-bottom:1px solid #E0DED8;font-size:12px">${escapeHtml(item.item || '')}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #E0DED8;font-size:12px">${escapeHtml(item.description || '')}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #E0DED8;font-size:12px;text-align:center">${escapeHtml(item.quantity)}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #E0DED8;font-size:12px;text-align:right">${formatCurrency(item.unitPrice)}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #E0DED8;font-size:12px;text-align:center">${item.discountPercent || 0}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #E0DED8;font-size:11px;text-align:center">${escapeHtml(item.tax || '')}</td>
      <td style="padding:8px 10px;border-bottom:1px solid #E0DED8;font-size:12px;text-align:right;font-weight:600">${formatCurrency(item.amount)}</td>
    </tr>
  `).join('');

  const generatedAt = new Date().toLocaleString(LOCALE.date);

  const html = `
    <html><head><title>${escapeHtml(BUSINESS.name)} — ${escapeHtml(doc.quoteNumber || doc.invoiceNumber || kind)}</title><style>
      body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #1A1A18; max-width: 820px; margin: 0 auto; font-size: 13px; }
      table { width: 100%; border-collapse: collapse; }
      th { background: #F5F4F0; }
      .footer { margin-top: 40px; padding-top: 14px; border-top: 1px solid #E0DED8; font-size: 10px; color: #9E9E98; }
    </style></head><body>
      <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:8px">
        ${doc.logo ? `<img src="${doc.logo}" alt="Logo" style="height:56px;max-width:140px;object-fit:contain" />` : '<div></div>'}
        ${statusBadge(status)}
      </div>

      <div style="font-size:30px;font-weight:900;margin-bottom:20px">${kind}</div>

      <div style="display:flex;gap:32px;margin-bottom:24px">
        <div style="flex:1">
          <div style="font-weight:600">${escapeHtml(doc.contactName || '')}</div>
          ${doc.clientAddress ? `<div style="color:#6B6B66">${escapeHtml(doc.clientAddress)}</div>` : ''}
          ${doc.clientSuburb ? `<div style="color:#6B6B66">${escapeHtml(doc.clientSuburb)}</div>` : ''}
          ${doc.clientCountry ? `<div style="color:#6B6B66">${escapeHtml(doc.clientCountry)}</div>` : ''}
        </div>
        <div style="flex:1">
          <div><span style="color:#9E9E98;font-size:10px;text-transform:uppercase;letter-spacing:0.05em">${dateLabel}</span><br/>${doc.date ? formatDate(doc.date) : ''}</div>
          ${expiryValue ? `<div style="margin-top:8px"><span style="color:#9E9E98;font-size:10px;text-transform:uppercase;letter-spacing:0.05em">${expiryLabel}</span><br/>${formatDate(expiryValue)}</div>` : ''}
          <div style="margin-top:8px"><span style="color:#9E9E98;font-size:10px;text-transform:uppercase;letter-spacing:0.05em">${numberLabel}</span><br/><strong>${escapeHtml(doc.quoteNumber || doc.invoiceNumber || '')}</strong></div>
        </div>
        <div style="flex:1;text-align:right">
          ${doc.businessName ? `<div style="font-weight:600">${escapeHtml(doc.businessName)}</div>` : ''}
          ${doc.businessAddress ? `<div style="color:#6B6B66">${escapeHtml(doc.businessAddress)}</div>` : ''}
          ${doc.businessSuburb ? `<div style="color:#6B6B66">${escapeHtml(doc.businessSuburb)}</div>` : ''}
          ${doc.businessPhone ? `<div style="color:#6B6B66">Phone: ${escapeHtml(doc.businessPhone)}</div>` : ''}
          ${doc.businessEmail ? `<div style="color:#6B6B66">${escapeHtml(doc.businessEmail)}</div>` : ''}
          ${doc.businessAbn ? `<div style="color:#6B6B66">${escapeHtml(doc.businessAbn)}</div>` : ''}
        </div>
      </div>

      ${(doc.tradeType || doc.licenceNo) ? `
      <div style="display:flex;gap:32px;margin-bottom:20px">
        ${doc.tradeType ? `<div><span style="color:#9E9E98;font-size:10px;text-transform:uppercase;letter-spacing:0.05em">Trade type</span><br/>${escapeHtml(doc.tradeType)}</div>` : ''}
        ${doc.licenceNo ? `<div><span style="color:#9E9E98;font-size:10px;text-transform:uppercase;letter-spacing:0.05em">Licence no.</span><br/>${escapeHtml(doc.licenceNo)}</div>` : ''}
      </div>` : ''}

      <table>
        <thead>
          <tr>
            <th style="padding:8px 10px;text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#6B6B66;font-weight:700">Item</th>
            <th style="padding:8px 10px;text-align:left;font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#6B6B66;font-weight:700">Description</th>
            <th style="padding:8px 10px;text-align:center;font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#6B6B66;font-weight:700">Qty</th>
            <th style="padding:8px 10px;text-align:right;font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#6B6B66;font-weight:700">Unit Price</th>
            <th style="padding:8px 10px;text-align:center;font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#6B6B66;font-weight:700">Disc %</th>
            <th style="padding:8px 10px;text-align:center;font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#6B6B66;font-weight:700">Tax</th>
            <th style="padding:8px 10px;text-align:right;font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#6B6B66;font-weight:700">Amount</th>
          </tr>
        </thead>
        <tbody>${itemsHTML}</tbody>
      </table>

      <div style="margin-top:20px;margin-left:auto;width:260px">
        <div style="display:flex;justify-content:space-between;padding:6px 0;font-size:13px"><span style="color:#6B6B66">Subtotal</span><span style="color:#E8611A;font-weight:600">${formatCurrency(doc.subtotal)}</span></div>
        <div style="display:flex;justify-content:space-between;padding:6px 0;font-size:13px"><span style="color:#6B6B66">GST</span><span style="color:#E8611A;font-weight:600">${formatCurrency(doc.gstAmount)}</span></div>
        <div style="display:flex;justify-content:space-between;padding:10px 0;font-size:16px;font-weight:700;border-top:2px solid #1A1A18"><span>Total ${LOCALE.currencyCode}</span><span>${formatCurrency(doc.total)}</span></div>
      </div>

      <div style="display:flex;gap:32px;margin-top:32px;border-top:1px solid #E0DED8;padding-top:20px">
        <div style="flex:1">
          ${doc.notes ? `<div style="font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#9E9E98;font-weight:700;margin-bottom:6px">Terms & Notes</div><div style="font-size:12px;color:#6B6B66;font-style:italic">${escapeHtml(doc.notes)}</div>` : ''}
        </div>
        <div style="flex:1">
          ${doc.paymentTerms ? `<div style="font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#9E9E98;font-weight:700;margin-bottom:6px">Payment Terms</div><div style="font-size:12px">${escapeHtml(doc.paymentTerms)}</div>` : ''}
          ${(doc.bankName || doc.bankBsb || doc.bankAccount) ? `
          <div style="margin-top:14px">
            <div style="font-size:10px;text-transform:uppercase;letter-spacing:0.05em;color:#9E9E98;font-weight:700;margin-bottom:6px">Bank Details</div>
            ${doc.bankName ? `<div style="font-size:12px">${escapeHtml(doc.bankName)}</div>` : ''}
            ${doc.bankBsb ? `<div style="font-size:12px">BSB: ${escapeHtml(doc.bankBsb)}</div>` : ''}
            ${doc.bankAccount ? `<div style="font-size:12px">Acc: ${escapeHtml(doc.bankAccount)}</div>` : ''}
          </div>` : ''}
        </div>
      </div>

      <div class="footer">Generated by ${escapeHtml(BUSINESS.name)} · ${generatedAt}</div>
    </body></html>
  `;

  printHTML(html);
}

// Re-export the formatter so callers (e.g. detail pages) don't need a second import
export { formatAmount };

export function exportQuote(quote) {
  exportBillingDocument({
    doc: quote,
    kind: 'QUOTE',
    status: getQuoteStatus(quote.status),
    dateLabel: 'Date',
    expiryLabel: 'Expiry',
    expiryValue: quote.validUntil,
    numberLabel: 'Quote number',
  });
}

export function exportInvoice(invoice) {
  exportBillingDocument({
    doc: invoice,
    kind: 'INVOICE',
    status: getInvoiceStatus(invoice.status),
    dateLabel: 'Invoice Date',
    expiryLabel: 'Due Date',
    expiryValue: invoice.dueDate,
    numberLabel: 'Invoice number',
  });
}
