import { DEFAULT_ROSTER } from '../constants/roster';
import { nowISO } from './client';

const NOW = nowISO();

export const seedEmployees = [
  { id: 'e1', name: 'Lars Hansen', role: 'Foreman',  phone: '+47 900 11 111', email: 'lars@pavemaster.no',  avatar: 'LH', color: '#EC4899', active: true, roster: { ...DEFAULT_ROSTER }, createdAt: NOW },
  { id: 'e2', name: 'Mia Olsen',   role: 'Operator', phone: '+47 900 22 222', email: 'mia@pavemaster.no',   avatar: 'MO', color: '#EC4899', active: true, roster: { ...DEFAULT_ROSTER }, createdAt: NOW },
  { id: 'e3', name: 'Erik Berg',   role: 'Laborer',  phone: '+47 900 33 333', email: 'erik@pavemaster.no',  avatar: 'EB', color: '#EC4899', active: true, roster: { days: ['wed','thu','fri','sat','sun'], startTime: '06:30', endTime: '17:30' }, createdAt: NOW },
  { id: 'e4', name: 'Sofia Dal',   role: 'Operator', phone: '+47 900 44 444', email: 'sofia@pavemaster.no', avatar: 'SD', color: '#EC4899', active: true, roster: { ...DEFAULT_ROSTER }, createdAt: NOW },
];

export const seedJobs = [
  {
    id: 'j1',
    referenceNumber: 'JOB-0001',
    description: 'Full resurfacing of 200m² driveway. Remove existing surface and lay new asphalt.',
    address: '14 Maple Street, Trondheim',
    status: 'book',
    startDate: '2026-04-03',
    startTime: '08:00',
    endDate: '2026-04-04',
    endTime: '16:00',
    contactName: 'Jan Nordmann',
    contactPhone: '+47 950 12 345',
    contactEmail: 'jan@example.com',
    assignedEmployees: ['e1', 'e2'],
    photos: [], documents: [], receipts: [],
    notes: 'Gate code: 1234',
    createdAt: NOW,
  },
  {
    id: 'j2',
    referenceNumber: 'JOB-0002',
    description: 'Patch cracks and apply sealcoat to 1,500m² parking area.',
    address: 'City Mall, Beddingen 8, Trondheim',
    status: 'quote',
    startDate: '2026-04-07',
    startTime: '07:00',
    endDate: '2026-04-09',
    endTime: '17:00',
    contactName: 'City Mall Management',
    contactPhone: '+47 730 00 000',
    contactEmail: 'facility@citymall.no',
    assignedEmployees: ['e1', 'e3', 'e4'],
    photos: [], documents: [], receipts: [],
    notes: '',
    createdAt: NOW,
  },
  {
    id: 'j3',
    referenceNumber: 'JOB-0003',
    description: 'Edge repair along 400m stretch.',
    address: 'Haakon VIIs gate, Trondheim',
    status: 'done',
    startDate: '2026-03-25',
    startTime: '06:00',
    endDate: '2026-03-25',
    endTime: '14:00',
    contactName: 'Trondheim Kommune',
    contactPhone: '+47 720 00 000',
    contactEmail: 'drift@trondheim.no',
    assignedEmployees: ['e2', 'e3'],
    photos: [], documents: [], receipts: [],
    notes: '',
    createdAt: NOW,
  },
  {
    id: 'j4',
    referenceNumber: 'JOB-0004',
    description: 'New asphalt surface for school yard.',
    address: 'Ladevegen 10, Trondheim',
    status: 'visit',
    startDate: '2026-04-10',
    startTime: '09:00',
    endDate: '',
    endTime: '',
    contactName: 'Lade Skole',
    contactPhone: '+47 732 12 000',
    contactEmail: 'admin@ladeskole.no',
    assignedEmployees: ['e1'],
    photos: [], documents: [], receipts: [],
    notes: 'Site visit only – bring camera',
    createdAt: NOW,
  },
];

export const seedQuotes = [
  {
    id: 'q1',
    quoteNumber: 'QUO-0001',
    jobId: 'j2',
    jobRef: 'JOB-0002',
    date: '2026-04-07',
    validUntil: '2026-05-07',
    status: 'sent',
    contactName: 'City Mall Management',
    clientAddress: 'Beddingen 8',
    clientSuburb: 'Trondheim, 7014',
    clientCountry: 'Norway',
    businessName: 'PaveMaster AS',
    businessAddress: 'Industriveien 12',
    businessSuburb: 'Trondheim, 7030',
    businessPhone: '+47 900 00 000',
    businessEmail: 'post@pavemaster.no',
    businessAbn: 'Org: 912 345 678',
    tradeType: 'Paving & Asphalt',
    licenceNo: 'PA-20198',
    items: [
      { id: 'qi1', item: 'Crack repair',  description: 'Patch cracks – 150m²',  quantity: 150,  unitPrice: 85, discountPercent: 0, tax: 'GST (15%)', amount: 12750 },
      { id: 'qi2', item: 'Sealcoat',      description: 'Application – 1,500m²', quantity: 1500, unitPrice: 25, discountPercent: 0, tax: 'GST (15%)', amount: 37500 },
      { id: 'qi3', item: 'Line marking',  description: 'Parking bay lines',     quantity: 1,    unitPrice: 4800, discountPercent: 0, tax: 'GST (15%)', amount: 4800 },
    ],
    subtotal: 55050,
    gstAmount: 8257.5,
    total: 63307.5,
    notes: 'Quote valid for 30 days. Work to be completed outside mall opening hours (18:00–07:00). All work guaranteed 12 months.',
    paymentTerms: '50% deposit, balance on completion',
    bankName: 'DNB',
    bankBsb: '1234',
    bankAccount: '1234.56.78901',
    logo: '',
    createdAt: NOW,
  },
];

export const seedInvoices = [
  {
    id: 'inv1',
    invoiceNumber: 'INV-0001',
    jobId: 'j3',
    jobRef: 'JOB-0003',
    quoteId: '',
    date: '2026-03-26',
    dueDate: '2026-04-09',
    status: 'awaiting_payment',
    contactName: 'Trondheim Kommune',
    clientAddress: 'Haakon VIIs gate',
    clientSuburb: 'Trondheim',
    clientCountry: 'Norway',
    businessName: 'PaveMaster AS',
    businessAddress: 'Industriveien 12',
    businessSuburb: 'Trondheim, 7030',
    businessPhone: '+47 900 00 000',
    businessEmail: 'post@pavemaster.no',
    businessAbn: 'Org: 912 345 678',
    items: [
      { id: 'ii1', item: 'Edge repair', description: '400m stretch', quantity: 400, unitPrice: 11.5, discountPercent: 0, tax: 'GST (15%)', amount: 4600 },
    ],
    subtotal: 4600,
    gstAmount: 690,
    total: 5290,
    notes: 'Payment within 14 days.',
    paymentTerms: 'Net 14 days',
    bankName: 'DNB',
    bankBsb: '1234',
    bankAccount: '1234.56.78901',
    logo: '',
    createdAt: NOW,
  },
];

export const seedTimeEntries = [
  { id: 'te1', employeeId: 'e1', jobId: 'j1', date: '2026-04-06', startTime: '08:00', endTime: '16:00', breakMinutes: 30, hours: 7.5,  notes: 'Prep and base layer', status: 'approved', createdAt: NOW },
  { id: 'te2', employeeId: 'e2', jobId: 'j1', date: '2026-04-06', startTime: '08:00', endTime: '16:00', breakMinutes: 30, hours: 7.5,  notes: '',                    status: 'approved', createdAt: NOW },
  { id: 'te3', employeeId: 'e1', jobId: 'j1', date: '2026-04-07', startTime: '08:00', endTime: '15:00', breakMinutes: 30, hours: 6.5,  notes: '',                    status: 'pending',  createdAt: NOW },
  { id: 'te4', employeeId: 'e3', jobId: 'j2', date: '2026-04-08', startTime: '07:00', endTime: '17:00', breakMinutes: 45, hours: 9.25, notes: 'Sealcoat day 1',      status: 'pending',  createdAt: NOW },
];
